baseURL: "https://ราคา.net/" # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: SEO คือ Search Engine Optimize การสร้างเว็บไซต์ให้มีประสิทธิภาพ และรองรับการติดอันดับบน Google
paginate: 5
# theme: hugo-PaperMod
defaultContentLanguage: en
enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: บทความ
                  url: archives
                  weight: 5
                - name: ค้นหา
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: ดูหนังAV
                  url: https://avfreex24.com/kissme/
                  weight: 10

    # th:
    #     languageName: "th"
    #     languageAltTitle: Thailand
    #     weight: 2
    #     title: เทคนิคการทำ Search Engine Optimize 
    #     profileMode:
    #         enabled: true
    #         title: SITE-SEO
    #         imageUrl: "/logo.svg"
    #         imageTitle: SITE-SEO ราคา.net
    #         imageWidth: 120
    #         imageHeight: 120
    #         subtitle: "☄️ Search | ☁️ Engine | 🌙 Optimize | 📱 Google"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Tags
    #               url: tags
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: Tags
    #               url: tags
    #               weight: 10
    #             - name: Categories
    #               url: categories
    #               weight: 10
    #             - name: Series
    #               url: series
    #               weight: 10
    #             - name: 100เรื่อง
    #               url: "https://100เรื่อง.com/"
    #             - name: PNCKDEVAPP
    #               url: "https://pnckdevapp.com/"
    #             - name: NullLink3
    #               url: "#"

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "ทำให้เว็บไซต์ของคุณติดอันดับอยู่ในลำดับต้นๆ ของผลการค้นหา ด้วยคีย์เวิร์ดหรือคำค้นหาที่คุณต้องการและเกี่ยวข้องกับธุรกิจของคุณ"
    author: PNCKDEVAPP

    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: false
    images: ["logo.svg"]

    profileMode:
        enabled: true
        title: สร้างเว็บไซต์ให้มีประสิทธิภาพ และรองรับการติดอันดับบน Google
        imageUrl: "/logo.svg"
        imageTitle: อันดับ Google
        imageWidth: 520
        # imageHeight: 120
        buttons:
            - name: บทความ
              url: archives
            - name: ประเภท
              url: tags

    # homeInfoParams:
    #     Title: "PaperMod"
    #     Content: >
    #         Welcome to demo of hugo's theme PaperMod.

    #         - **PaperMod** is a simple but fast and responsive theme with useful feature-set that enhances UX.

    #         - subtitle: "☄️ Search | ☁️ Engine | 🌙 Optimize | 📱 Google"

    #         - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    socialIcons:
        #- name: github
        #  url: "https://github.com/adityatelange/hugo-PaperMod"
        #- name: KoFi
        #  url: "https://ko-fi.com/adityatelange"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https://pnckdevapp.com/"
        Text: "แนะนำแก้ไข" # edit text
        appendFilePath: true # to append file path to Edit link

    label:
         text: "Home"
         icon: logo.svg
         iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
         favicon: "favicon.png"
         favicon16x16: "favicon.png"
         favicon32x32: "favicon.png"
         apple_touch_icon: "favicon.png"
         safari_pinned_tab: "favicon.png"

    cover:
        hidden: false # hide everywhere but not in structured data
        hiddenInList: false # hide on list pages and home
        hiddenInSingle: false # hide on single page

    fuseOpts:
        isCaseSensitive: true
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true